apiVersion: v1
kind: ConfigMap
metadata:
  name: front-configmap
data:
  port-bff: 3001
  url-front: http://localhost:3000
  api-clients: http://localhost:8080/api/v1
  api-transactions: http://localhost:8081/api/v1
  react-app-bff: http://localhost:3001/api
