apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front-bff
spec:
  template:
    spec:
      containers:
        - name: front
          env:
            - name: SPRING_DATASOURCE_URL
              value: any
        - name: front-bff
          env:
            - name: SPRING_DATASOURCE_URL
              value: any
