apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 80 # Es el portero
      name: api-clients
      targetPort: 8080 # Port Api 1
      protocol: TCP
    - port: 81 # Es el portero
      name: api-transactions
      targetPort: 8081 # Port Api 2
      protocol: TCP
  type: LoadBalancer
